### ISSUE TITLE
Command executed:GRCh38.p14

### ISSUE THREAD

**Issue by singha30** [hbctraining/variant_analysis#8]
Command executed:

bcftools annotate --header-lines /Data/data/raja/cfdna/nextflow1/bin/syn3_header.txt LCR_FILTERED > FILTERED_hd.vcf
**java -jar -Xmx4g /Data/data/raja/cfdna/nextflow1/bin/snpEff/snpEff.jar eff -dataDir /Data/data/raja/cfdna/nextflow1/bin
/snpEff/data -cancer -noLog -csvStats CSV_STATS -s HTML_REPORT /Data/data/raja/cfdna/nextflow1/bin/snpEff/Data/data/GRCh38.p14 FILTERED_hd.vcf > SNPEFF_ANNOTATED.vcf**
java -jar /Data/data/raja/cfdna/nextflow1/bin/SNPEFF/SnpSift.jar annotate /Data/data/raja/cfdna/nextflow1/bin/snpEff/DBS
NP_DATABASE -tabix -noLog SNPEFF_ANNOTATED.vcf > DBSNP_ANNOTATED.vcf

Command exit status:
255

Command output:
(empty)

### Command error:
**java.lang.RuntimeException: Property: '/Data/data/raja/cfdna/nextflow1/bin/snpEff/Data/data/GRCh38.p14.genome' not found**
at org.snpeff.interval.Genome.(Genome.java:103)
at org.snpeff.snpEffect.Config.readConfig(Config.java:757)
at org.snpeff.snpEffect.Config.init(Config.java:532)
at org.snpeff.snpEffect.Config.(Config.java:119)
at org.snpeff.SnpEff.loadConfig(SnpEff.java:449)
at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:883)
at org.snpeff.snpEffect.commandLine.SnpEffCmdEff.run(SnpEffCmdEff.java:869)
at org.snpeff.SnpEff.run(SnpEff.java:1173)
at org.snpeff.SnpEff.main(SnpEff.java:163)

1. error is show:-GRCh38.p14.genome' not found 
**can you please help how to generate this file  or fix the issue  **

_Originally posted by @singha30 in https://github.com/hbctraining/variant_analysis/issues/7#issuecomment-1898518218_

**Comment by Gammerdinger** [comment]
In SnpEff build 4.3g, these are the pre-built GRCh38 builds:

GRCh38.86
GRCh38.p7.RefSeq

It looks like you are trying to run GRCh38.p14, which I am not sure is supported as a pre-built build and maybe that's why it can't find the file. Also, our course materials have overgone a lot of work since this issue was opened, so this issue might be a bit outdated. As a result, I am going to close the issue, but if the problem persists, please open a new issue based upon the new materials. Thank you!

Best,
Will Gammerdinger
