### ISSUE TITLE
self-learning.md links

### ISSUE THREAD

**Issue by benjibromberg** [hbctraining/variant_analysis#9]
Hi! I know this module is still under development for official release, but I'm currently learning variant calling and I've loved your past learning materials so I've been using this as it seems largely completed.

I wanted to share a few issues I found with the lesson links on `self-learning.md` that I noticed using this unfinished version of the course with GitHub Pages:

1. Lesson 3 links to `03_file_formats.md` not `00_file_formats.md` as the actual file is named
2. Lesson 4 links to `04_fastqc.md` not `03_fastqc.md` as the actual file is named
3. Lesson 5 links to `05_sequence_alignment_theory.md` not `04_sequence_alignment_theory.md` as the actual file is named

Thank you for all the work on this module and all other HBC learning modules!! They're absolutely fantastic!!

**Comment by Gammerdinger** [comment]
Thank you for the kind words and help! This material is under active development and we anticipate it to be in near alpha testing status in the upcoming week or so. We are aware of these links being broken since we are currently shuffling material around and that's why the links are in the state that they are. I am going to assign this to myself and I won't close it until I am sure the links have been fixed. Thank you for your diligent observations and we hope that you find the materials to be helpful (despite the alpha-ish state that they are in).

Best,
Will

**Comment by Gammerdinger** [comment]
Okay. We spent some time today getting what we believe will be the finally ordering of the lessons and cleaning up the lessons a bit. I have tested the links and I think they work how we envision them working. Let me if they don't otherwise, I will close the issue in a few days.
